export interface Planos {
  cod: string;
  descrip: string;
  codDescr1?: string;
  descrip1?: string;
  fAlta1?: string;
  fBaja1?: string;
  pathFic1?: string;
  codDescr2?: string;
  descrip2?: string;
  fAlta2?: string;
  fBaja2?: string;
  pathFic2?: string;
  codDescr3?: string;
  descrip3?: string;
  fAlta3?: string;
  fBaja3?: string;
  pathFic3?: string;
  codDescr4?: string;
  descrip4?: string;
  fAlta4?: string;
  fBaja4?: string;
  pathFic4?: string;
  codDescr5?: string;
  descrip5?: string;
  fAlta5?: string;
  fBaja5?: string;
  pathFic5?: string;
}
